version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "s3://tandy-io-prod/"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Executing Install Phase
      - echo Installing NPM and Angular CLI Dependencies...
      - npm install
      - npm install -g @angular/cli 
    finally:
      - echo Executing Install Finally  
  build:
    commands:
      - echo Executing Build Phase
      - ng build
    finally:
      - echo Executing Build Finally
  post_build:
    commands:
      - echo Executing Post Build Phase
      - echo Pushing dist to S3 at $PATH
      - aws s3 cp dist s3://tandy-io-prod/ --recursive --acl public-read 
    finally:
      - echo Executing Post Build Finally  
artifacts:
  files:
    -'**/*'
  base-directory: 'dist'
  discard-paths: yes