version: 0.2

env:
  variables:
    ENV: "prod"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Executing Install Phase
      - echo Installing NPM and Angular CLI Dependencies...
      - npm install
      - npm install -g @angular/cli 
    finally:
      - echo Executing Install Finally  
  build:
    commands:
      - echo Executing Build Phase
      - ng build
    finally:
      - echo Executing Build Finally
  post_build:
     commands:
       - echo Executing Post Build Phase
     finally:
       - echo Executing Post Build Finally  
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes