version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "s3://tandy.io.s3.amazonaws.com/"
    BUILD_FOLDER: "dist"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Executing Install Phase
      - echo Installing NPM and Angular CLI Dependencies...
      - npm install
      - npm install -g @angular/cli 
    finally:
      - echo Executing Install Finally  
  build:
    commands:
      - echo Executing Build Phase
      - ng build
    finally:
      - echo Executing Build Finally
  post_build:
    commands:
      - aws s3 cp ${BUILD_FOLDER} ${S3_BUCKET} --recursive --cache-control max-age=${CACHE_CONTROL}
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes